<?php

namespace App\Services;

use App\Repositories\OperationRepository;
use Illuminate\Support\Facades\Auth;

class OperationService extends BaseService
{
    public function __construct(OperationRepository $operationRepository)
    {
        parent::__construct($operationRepository);
    }

    public function rules($action = "store"): array
    {
        return [
            'company_id' => 'nullable|integer|exists:companies,id',
            'parent_id' => 'nullable|integer|exists:operations,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'approval_date' => 'nullable|date',
            'start_date' => 'nullable|date',
            'completion_date' => 'nullable|date|after_or_equal:start_date',
            'nc_amount' => 'nullable|numeric|min:0',
            'total_amount' => 'nullable|numeric|min:0',
            'fiscal_year' => 'nullable|integer|min:2000|max:2100',
        ];
    }

    public function store(array $data)
    {
        return parent::store([
            ...$data,
            'user_id' => Auth::id(),
        ]); // TODO: Change the autogenerated stub
    }
}
